URL updates and update to cma rereqs
NeuromatchAcademy/precourse pull request #119
Opened 2024-02-27 20:52 UTC by courtneydean33

2024-02-28 18:19 UTC, iamzoltan requested changes
Looks good! Can you fix the one url?

2024-02-28 18:19 UTC, iamzoltan commented on prereqs/ClimateScience.md
> +Welcome to the [Climatematch Academy](https://neuromatch.io/computational-neuroscience-course/)! We're really excited to bring this course to such a wide and varied audience. We want to make sure eve
the url is wrong

2024-03-19 21:16 UTC, courtneydean33 commented
@iamzoltan why didn't this get merged? I just checked an that URL is correct i think?

2024-04-25 19:38 UTC, iamzoltan approved these changes

2024-04-25 19:38 UTC, merged